version: 2
general:
  branches:
    only:
      - main
      - staging
      - dev
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: create workspace
          command: mkdir -p /tmp/workspace
      - run:
          name: Install awsebcli package
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install build-essential python3-pip
            sudo pip install --upgrade awsebcli
            eb --version
#      - run:
#          name: installing dependencies
#          command: |
#            npm  install
      - run:
          name: deploy 
          command: |
           bash ./deploy.sh
      - run:
          name: Removing aws config
          command: |
            rm -rf /home/circleci/.aws
      - run: ls /tmp/workspace
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - status.txt`