version: "3.7"

volumes:
  vol-emqx-data:
    name: foo-emqx-data
  vol-emqx-log:
    name: foo-emqx-log


services:

  node:
    container_name: node
    image: "node:14"
    restart: always
    working_dir: /home/ec2-user/app
    volumes:
      - ./app/:/home/node/app
    ports:
      - "3000:3000"
      - "3001:3001"
      - "80:3002"

    links:
      - emqx
      - mongo

    command: sh -c "echo 'delaying 30 seconds' && sleep 30 && npm run start"
    #command: sh -c "npm install"

  mongo:
    container_name: mongo
    image: mongo:4.4
    restart: always
    logging:
      driver: "none"
    environment:
      TZ: "${TZ}"
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
    volumes:
      - ./mongodata:/data/db
    ports:
      - ${MONGO_EXT_PORT}:27017

