version: "3.8"
#
volumes:
  vol-emqx-data:
    name: foo-emqx-data
# vol-emqx-etc:
  # name: foo-emqx-etc
  vol-emqx-log:
    name: foo-emqx-log



services:
  node:
    container_name: node
    image: "nuxt_app:latest"
    restart: always
    environment:
      API_PORT: ${API_PORT}
      WEBHOOKS_HOST: ${WEBHOOKS_HOST}
      HOST: ${HOST}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_DATABASE: ${MONGO_DATABASE}
      EMQX_DEFAULT_APPLICATION_SECRET: ${EMQX_DEFAULT_APPLICATION_SECRET}
      EMQX_NODE_SUPERUSER_USER: ${EMQX_NODE_SUPERUSER_USER}
      EMQX_NODE_SUPERUSER_PASSWORD: ${EMQX_NODE_SUPERUSER_PASSWORD}
      EMQX_API_TOKEN: ${EMQX_API_TOKEN}
      AUTH_TOKEN_PASSWORD: ${AUTH_TOKEN_PASSWORD}
      EMQX_RESOURCES_DELAY: ${EMQX_RESOURCES_DELAY}
      APP_PORT: ${APP_PORT}
      AXIOS_BASE_URL: ${AXIOS_BASE_URL}
      MQTT_PORT: ${MQTT_PORT}
      MQTT_HOST: ${MQTT_HOST}
      MQTT_PREFIX: ${MQTT_PREFIX}
      SSLREDIRECT: ${SSLREDIRECT}
    working_dir: /usr/src/nuxt-app
    volumes:
      - ./nuxtdata/:/usr/src/nuxtdata
    ports:
      - "3000:3000"
      - "3001:3001"
      - "80:3002"

    links:
      - emqx
      - mongo

    command: sh -c "echo 'delaying 30 seconds' && sleep 30 && npm run start"
    #command: sh -c "npm install"

  mongo:
    container_name: mongo
    image: mongo:4.4
    restart: always
    environment:
      TZ: "${TZ}"
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
    volumes:
      - ./mongodata:/data/db
    ports:
      - ${MONGO_EXT_PORT}:27017

  emqx:
    container_name: emqx
    image: emqx/emqx:4.2.3
    restart: always
    ports:
      - 18083:18083
      - 1883:1883
      - 8883:8883
      - 8083:8083
      - 8085:8081

    volumes:
      - vol-emqx-data:/opt/emqx/data
      - vol-emqx-log:/opt/emqx/log

    #command: 
    #   sh -c "sudo chown emqx:emqx /opt/emqx/log/ /opt/emqx/data/"
    #   sh -c "echo "Set disable_coredump false" >> /etc/sudo.conf"
    
    links:
      - mongo

    extra_hosts:
      - "localhost:${HOST}"

    environment:
      EMQX_NAME: bits4bees_broker
      EMQX_HOST: 127.0.0.1

      TZ: "${TZ}"

      # DEFAULT DASH PASS
      EMQX_DASHBOARD__DEFAULT_USER__PASSWORD: "${EMQX_DEFAULT_USER_PASSWORD}"

      # DEFAULT APP SECRET
      EMQX_MANAGEMENT__DEFAULT_APPLICATION__SECRET: "${EMQX_DEFAULT_APPLICATION_SECRET}"

      EMQX_ALLOW_ANONYMOUS: "false"
      EMQX_NOMATCH: "deny"

      # MONGO CONNECTION
      EMQX_AUTH__MONGO__TYPE: single
      EMQX_AUTH__MONGO__TOPOLOGY__POOL_SIZE: 1
      EMQX_AUTH__MONGO__TOPOLOGY__MAX_OVERFLOW: 0

      EMQX_AUTH__MONGO__SERVER: "mongo:${MONGO_EXT_PORT}"
      EMQX_AUTH__MONGO__POOL: 8

      EMQX_AUTH__MONGO__LOGIN: "${MONGO_USERNAME}"
      EMQX_AUTH__MONGO__PASSWORD: "${MONGO_PASSWORD}"
      EMQX_AUTH__MONGO__AUTH_SOURCE: admin

      EMQX_AUTH__MONGO__DATABASE: "${MONGO_DATABASE}"
      EMQX_AUTH__MONGO__AUTH_QUERY__COLLECTION: "emqxauthrules"

      EMQX_AUTH__MONGO__SUPER_QUERY__COLLECTION: "emqxauthrules"
      EMQX_AUTH__MONGO__SUPER_QUERY__SUPER_FIELD: "is_superuser"
      EMQX_AUTH__MONGO__SUPER_QUERY__SELECTOR: "username=%u"
      EMQX_AUTH__MONGO__SUPER_QUERY: "off"

      EMQX_AUTH__MONGO__AUTH_QUERY__PASSWORD_HASH: plain
      EMQX_AUTH__MONGO__AUTH_QUERY__PASSWORD_FIELD: "password"
      EMQX_AUTH__MONGO__AUTH_QUERY__SELECTOR: "username=%u"

      ## Enable ACL query.
      #Access control list
      EMQX_AUTH__MONGO__ACL_QUERY: "on"
      EMQX_AUTH__MONGO__ACL_QUERY__COLLECTION: "emqxauthrules"
      EMQX_AUTH__MONGO__ACL_QUERY__SELECTOR: "username=%u"

      EMQX_LOADED_PLUGINS: "emqx_recon,emqx_retainer,emqx_management,emqx_dashboard,emqx_auth_mongo"

      # listener.tcp.external.max_connections
      EMQX_LISTENER__TCP__EXTERNAL__MAX_CONNECTIONS: 10
      
      # listener.tcp.internal.max_connections
      EMQX_LISTENER__TCP__INTERNAL__MAX_CONNECTIONS: 10

      # dashboard.listener.https.max_clients
      EMQX_DASHBOARD__LISTENER__HTTP__MAX_CLIENTS: 10
      
      # management.listener.http.max_clients
      EMQX_MANAGEMENT__LISTENER__HTTP__MAX_CLIENTS: 5
      
      # listener.ssl.external.max_connections
      EMQX_LISTENER__SSL__EXTERNAL__MAX_CONNECTIONS: 10

      # listener.ws.external.max_connections
      EMQX_LISTENER__WS__EXTERNAL__MAX_CONNECTIONS: 10

      # listener.wss.external.max_connections
      EMQX_LISTENER__WSS__EXTERNAL__MAX_CONNECTIONS: 10
      
