FROM node:14

RUN mkdir -p /usr/src/nuxt-app
WORKDIR /usr/src/nuxt-app

# RUN apt-get update -y && apt-get upgrate -y
# RUN apt-get add git

COPY . /usr/src/nuxt-app/
RUN npm install

RUN npm run build

EXPOSE 3000
EXPOSE 3001
EXPOSE 3002

# ENV HOST = 0.0.0.0

# ENV PORT = 3000

CMD [ "npm","start" ]



