version: "3.8"


services:

  node:
    container_name: node
    image: "nuxt_app:latest"
    restart: always
    working_dir: /usr/src/nuxt-app
    volumes:
      - ./nuxtdata/:/usr/src/nuxtdata
    ports:
      - "3000:3000"
      - "3001:3001"
      - "80:3002"